/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        serif: ["Playfair Display", "Georgia", "Times New Roman", "serif"],
        sans:  ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono:  ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      colors: {
        // ── Flat CSS-var tokens (no opacity modifier) ───────────────────────
        "rv-bg":           "var(--rv-bg)",
        "rv-surface":      "var(--rv-surface)",
        "rv-surface2":     "var(--rv-surface2)",
        "rv-border":       "var(--rv-border)",
        "rv-border2":      "var(--rv-border2)",
        "rv-accent-soft":  "var(--rv-accent-soft)",
        "rv-success-soft": "var(--rv-success-soft)",
        "rv-warning-soft": "var(--rv-warning-soft)",
        "rv-danger-soft":  "var(--rv-danger-soft)",
        // ── Opacity-capable CSS-var tokens ──────────────────────────────────
        "rv-accent":  "rgb(var(--rv-accent) / <alpha-value>)",
        "rv-text":    "rgb(var(--rv-text) / <alpha-value>)",
        "rv-muted":   "rgb(var(--rv-muted) / <alpha-value>)",
        "rv-subtle":  "rgb(var(--rv-subtle) / <alpha-value>)",
        "rv-success": "rgb(var(--rv-success) / <alpha-value>)",
        "rv-warning": "rgb(var(--rv-warning) / <alpha-value>)",
        "rv-danger":  "rgb(var(--rv-danger) / <alpha-value>)",
        // ── Mediterranean scale palettes ─────────────────────────────────────
        "rv-olive": {
          DEFAULT: "rgb(var(--rv-olive) / <alpha-value>)",
          50:  "#f6f7f0",
          100: "#e8ecda",
          200: "#d1d9b5",
          300: "#b3c285",
          400: "#94a85a",
          500: "#738a3e",
          600: "#586d2f",
          700: "#435425",
          800: "#313d1c",
          900: "#1e2610",
        },
        "rv-sea": {
          DEFAULT: "rgb(var(--rv-sea) / <alpha-value>)",
          50:  "#eef8fb",
          100: "#d4eef5",
          200: "#a8dcea",
          300: "#72c4db",
          400: "#3da8ca",
          500: "#2189ae",
          600: "#196d8e",
          700: "#135470",
          800: "#0e3d52",
          900: "#092838",
        },
        "rv-sand": {
          50:  "#fdfcf8",
          100: "#f8f4ea",
          200: "#f0e8d0",
          300: "#e5d5ad",
          400: "#d4ba7e",
          500: "#c09a4f",
          600: "#a07838",
          700: "#7d5828",
          800: "#5c3f1c",
          900: "#3a270f",
        },
        "rv-cream": "#faf9f4",
        "rv-dark":  "#111810",
        // ── Legacy named swatches ────────────────────────────────────────────
        "med-terracotta": "#C65D3B",
        "med-sand":       "#F2E9DC",
        "med-sea":        "#3A6F73",
        "med-olive":      "#6A7B4F",
      },
    },
  },
  plugins: [],
};
